### ISSUE TITLE
Recheck default view when UI upgrades arrive

### ISSUE THREAD

**Issue by apotterri** [land-of-apps/resque#7]
The UI as of 20200827 doesn't show much at the default level of detail:
![image](https://user-images.githubusercontent.com/4212483/91492091-032f1b00-e883-11ea-9a92-e8c54ff834d9.png)

See if this is improved in subsequent releases.

**Comment by jaredKreppein** [comment]
Resque now shows much more detail at default level

![Screen Shot 2020-10-28 at 9 46 43 AM](https://user-images.githubusercontent.com/59896799/97460594-852ed500-1902-11eb-988d-f86eca186bd9.png)
